### ISSUE TITLE
[Feature] Beacons to unexplored areas

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#117]
https://forum.audiogames.net/post/861761/#p861761

> I wonder if it is possible for the mod to include some kind of unexplore room or unexplore space pathfinding where you can navigate to it, this ensure for the player not to get lost and can fully explore the map.

**Comment by Alando1-doom** [comment]
That is a good question if this is possible. In a way this would act like the audio version of the gray areas on the computer map. Although an interesting and neat idea, I'm not sure if it is possible.

**Comment by proydoha** [comment]
I mean... It is possible "on paper". But there are plenty of ways it could go wrong.

**Comment by proydoha** [comment]
Added in #148 
Or at least experimental version of it.
