### ISSUE TITLE
[Feature] Implement togglable proximity detector

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#120]
Prototype
[Toby-Proximity-Prototype-Front-Back-Pitch.zip](https://github.com/user-attachments/files/16639602/Toby-Proximity-Prototype-Front-Back-Pitch.zip)

Thread: https://forum.audiogames.net/post/862511/#p862511
> The one thing that I find myself missing is a way to detect when you're close to a wall and when a nearby wall ends and a new passage opens up either to your left or right. Systems like that are quite common in audiogames like Shades of Doom from GMA Games, the JRPGs from VGstorm etc. Basically there is a soft non-intrusive sound, like a wind chime for example,  as you approach a wall. This sound ceases if there is an opening in the wall, thus letting you know that you can proceed in that direction.

**Comment by Alando1-doom** [comment]
I do remember you had a concept for the drop-off detection system, where it not only detected drop-offs, but the proximity to a wall/surface. We could consider bringing this concept back in a different form. To have it togglable, too, is a good idea. Perhaps have it switch on/off like a flashlight. I guess it would act as a radar of some sort like in Iron Lung. Jarewill put together an Iron Lung game for Doom not too long ago. Perhaps we could ask how he went about wall detection scripts.

**Comment by proydoha** [comment]
Its basically implemented. PR is a draft because I knew that there will be merge conflicts.

**Comment by proydoha** [comment]
Merge conflicts resolved, you can review and merge it.

**Comment by Alando1-doom** [comment]
Awesome - I'll take care of it now :)
