### ISSUE TITLE
[Feature] Universal footsteps not attached to player class

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#124]
Additional requirement: footsteps should only make sound if player is actually moving. If player is stuck there should be no footsteps sound.

This way we'll achieve the following:
- Wall collision sound + footsteps = player is brushing against the wall but still able to move
- Wall collision sound, no footsteps = player is stuck

**Comment by Alando1-doom** [comment]
I did come across a wad not too long ago where it played footstep sounds based on the player's movement, speed, and whether they were on the floor or not. It, too, is able to play terrain sounds depending on what flat texture the player is walking on. I came across one for Heretic recently. I think I have the other one somewhere on my computer. I'll hunt it down and I'll let you know what I find. If I have it, we can possibly utilize this wad for the Toby Accessibility Mod.

**Comment by proydoha** [comment]
This is one of the most frequent complaints when Toby Doom is loaded with other mods: no footsteps sound.

**Comment by Alando1-doom** [comment]
I have found the wad that creates footstep sounds. It can be found on this zdoom forum thread:
https://forum.zdoom.org/viewtopic.php?t=60401
I'll send this to you via the zdoom forum Private Message system as well.
The creator behind this is Denis Belmondo and this mod is based on one that The Zombie Killer put together long ago. This version uses ZScript to generate the sounds. Seems very versatile and looks like it can be adapted to cover Doom, Heretic, & Hexen. I'll still keep the TERRAIN lump file active for the liquids and I will change some sounds in this ZFootstep mod - some of the liquid sounds in there are a bit underwhelming. Let me know what you think.

**Comment by proydoha** [comment]
I think this was added
