### ISSUE TITLE
[QoL] WallHit projectiles can hit shield actors attached to players by some mods and they shouldn't

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#132]
https://forum.audiogames.net/post/867043/#p867043

> The problems are when you pick up the sword you constantly get the wall bump noise, which while distracting

WallHit projectiles are hitting floor because player actor is too short?

**Comment by proydoha** [comment]
Actually. I don't think that's the source of a problem here.
The source of the problem is that player has a shield attached to and wall detecting projectiles hit that shield.

**Comment by Alando1-doom** [comment]
If the custom weapon is spawning an invisible actor, it is likely the Impact Detection projectiles are coming into contact with it. I would imagine the weapon indicated has some kind of blocking ability. I would have to take a closer look at the mod itself and look deeper into the code to see how everything was coded.

**Comment by proydoha** [comment]
Just so that I didn't forget: the item in question is "Sheeld" from LegendOfDoom.
