### ISSUE TITLE
[Bug] Annoying console output

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#134]
When game starts I can see annoying console output:

```
P_StartScript: Unknown script 0
P_StartScript: Unknown script 0
P_StartScript: Unknown script 0
P_StartScript: Unknown script 0
P_StartScript: Unknown script 0
P_StartScript: Unknown script 0
```

And in Toby Heretic its
```
P_StartScript: Unknown script "Ironlich"
P_StartScript: Unknown script "Knight"
P_StartScript: Unknown script "KnightGhost"
P_StartScript: Unknown script "Minotaur"
P_StartScript: Unknown script "Mummy"
P_StartScript: Unknown script "MummyGhost"
```

I would like to hunt it down and remove

**Comment by Alando1-doom** [comment]
I noticed this as well. Part of me thinks it might have something to do with the ACS scripts. It is possible there may be something with one or more of the ACS scripts that might be causing this weird behavior.

**Comment by proydoha** [comment]
Annoying console output is caused by `WEAROFF` script
