### ISSUE TITLE
[Development] Missing sounds / narration

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#143]
I am starting to forget about it so I'm creating this issue.

Currently we have following sounds missing

For menu system, when there are no menu items in the menu (for example this can happen when navigating to "Remove nearest marker" and there are no markers nearby):
- menusnd/nomenuitems - "No menu items"

~For crouching:~
~- stats/general/crouched~
~- stats/general/uncrouched~

**Comment by Alando1-doom** [comment]
Crouch sounds have been added. I'll do a voiceover for the "No Menu Items" in the next update.

**Comment by Alando1-doom** [comment]
"No Menu Items" has been implemented in the menu sounds archive. All good to go :)
