### ISSUE TITLE
Hexen Player Class Menu - Narrator won't announce that the player is currently in the player class menu.

### ISSUE THREAD

**Issue by Alando1-doom** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#164]
When the player is brought to the player class selection menu, the narrator doesn't announce that the player is currently in the menu. Even though the narrator does tell the player what player class they have selected, it's the "Choose Player Class" announcement that isn't working.

**Comment by proydoha** [comment]
I thought we've figured it out ( ? )
