### ISSUE TITLE
Updates for Armor Stat Checker to include Hexen Armor

### ISSUE THREAD

**Issue by Alando1-doom** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#165]
If possible, we need to update the Armor Stat Checker to include Hexen armor.

**Comment by proydoha** [comment]
This one is definitely possible but is tricky.

**Comment by proydoha** [comment]
From what I am seeing: https://github.com/ZDoom/gzdoom/blob/master/wadsrc/static/zscript/actors/inventory/armor.zs#L454-L455

There are two arrays we want to look at:
Slots and SlotsIncrement

SlotsIncrement determines how much armor each of the 4 armor pieces provides for each class
Slots determines actual armor values. So when you pick up an item - it is equal to SlotsIncrement value. But then as you take damage it gradually goes down.

The only worrying part is that now it is possible to define your own BasicArmor and HexenArmor:
https://zdoom.org/wiki/MAPINFO/GameInfo_definition#BasicArmorClass
But I think we can ignore this for now.

**Comment by proydoha** [comment]
However there seem to be no way of tracking those values in UI as far as I can see. So what should we actually communicate in armor checker? That armor piece is equipped?

Or would we give number breakdown for each armor piece?

**Comment by Alando1-doom** [comment]
The breakdown seems to be a logical approach.

**Comment by proydoha** [comment]
I've included both:
- total + detailed breakdown
- simplified: total + currently occupied slots
Simplified is default.

**Comment by Alando1-doom** [comment]
Awesome :) I just tried it out and it works beautifully. Excellent work! I, too, just took care of the new voiceovers and updated the Hexen armor SNDINFO. Pull Request is ready for review.
