### ISSUE TITLE
[Bug] Sound discrepancy

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#25]
There is a discrepancy between different sounds

| Doom actor class | Toby actor class | Actor-in-viewport sound | Pickup sound | Player status sound |
| --- | --- | --- | --- | --- |
| Infrared | NightVisors | Night visor | Night vision goggles | - |
| RadSuit | BioSuit | Radsuit | Biosuit | - |
| GreenArmor | GreenArmor_Pickup | Green armor | Armor | Green armor |
| BlurSphere | Invisibility | Blur sphere | Partial invisibility | - |

**Comment by Alando1-doom** [comment]
Updated the sounds in the ProjectToby_Guns_V7.wad and TobyPowerups.wad. Will upload updated files soon.
