### ISSUE TITLE
[Feature?] Separate Toby Core mod, Toby Weapons and Toby Monsters

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#26]
I propose to separate core mod from weapons and monsters into separate repositories and manage them independently so that it would be possible to load only Core + Weapons or Core + Monsters or just Core with any other weapon or monster mod.

**Comment by Alando1-doom** [comment]
Guns, Monsters, Pickups, and Decorations are now separate from the Core Mod :) These pieces will now be stored in a folder within the Toby Accessibility Mod V7 Folder named "Addons." Batch files have been updated to reflect the files' new location. Everything is working well :)
