### ISSUE TITLE
[Add-on idea] Area Scanner System can detect Doors and Switches

### ISSUE THREAD

**Issue by Alando1-doom** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#51]
While playing around with the Area Scanner System, I thought it might be pretty cool to have the system pick up on the beacon "monsters" situated in front of doors and switches. It might be able to help the player gauge where doors are to help them with navigation.

**Comment by proydoha** [comment]
It already can detect them:
![image](https://github.com/Alando1-doom/Toby-Accessibility-Mod-for-Doom/assets/44492748/80163ee7-abe5-40da-91c0-6ebb447c5451)

You can create sound definitions from them and it'll just work.
My only concern for it is that when the door is open (and it can be activated from both sides) Area Scanner will announce two doors for one "doorway":
![image](https://github.com/Alando1-doom/Toby-Accessibility-Mod-for-Doom/assets/44492748/0fcffe7f-9776-4769-b8c4-af0c8cecabb6)

**Comment by Alando1-doom** [comment]
Awesome! I just recorded the voiceovers for them and I will implement them right away. Thank you :)

**Comment by proydoha** [comment]
Just communicate the caveat of double doors in your audio guide because I imagine that this will be confusing.
