### ISSUE TITLE
[Feature] Add sounds for opening and closing console

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#62]
This also includes full screen console when game throws ZScript error.

**Comment by Alando1-doom** [comment]
I like this idea :) Would you like me to record voiceovers for this?
"Console Open" "Console Closed"

**Comment by proydoha** [comment]
Definitely

And also this:"Full screen console opened. Most likely an error occurred."

Optionally you can also provide an information how to report this kind of error but I'm not sure how blind-accessible this would be.
Option 1: ask to type "screenshot" and press "Enter" - this will save a screenshot of a console in screenshots folder in game's directory (I think?). The problem here is that there will be no audio feedback of what is going on. 
Option 2: include "+logfile log.txt" launch parameter in .bat files and ask to send "log.txt" to you before starting the game again. Because starting the game again will override the log.

And finally I think pressing Esc will return you to main menu from this state so you can inform about that.

And all of it should be a single audio file.
