### ISSUE TITLE
[Feature] 180 degree turn

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#63]
Mentioned in this zdoom forums post:
[https://forum.zdoom.org/viewtopic.php?p=1249520#p1249520](https://forum.zdoom.org/viewtopic.php?p=1249520#p1249520)

**Comment by Alando1-doom** [comment]
Sure. I can rebind the key. I can make X the 180 degree turn.

**Comment by Alando1-doom** [comment]
Jarewill took care of this feature. Will be integrating code into mod.
