### ISSUE TITLE
[BUG] Core-only fails to load without beacons

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#70]
Beacon actors for doors and exits were removed from Core mod and Core-only fails to load without them.

~~Mildly related issue: there is a `Version "3.0"` in first line of `linespawner.zs`, it needs to be removed as version is defined in `zscript.zs`~~ Fixed by #71

**Comment by Alando1-doom** [comment]
Issue Resolved. "Version 3.0" was removed from the script. Everything is operational.

**Comment by proydoha** [comment]
Reopened. The issue with "Version" is fixed but it still fails to load without beacons.

**Comment by Alando1-doom** [comment]
I found the issue - DEC_BEAC was in TobyV7_Pickups.pk3. I had just transferred DEC_BEAC to the Core Mod and everything is working. The Core Mod is able to run without issue. Pull Request is standing by. Be sure to update your copy of TobyV7_Pickups.pk3 by removing DEC_BEAC.

Good catch :)
