### ISSUE TITLE
[Bug] "<Key type> key is required" announcement needs to be adjusted to work in Heretic

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#77]
It fails on two fronts:
1. Wrong key color is announced when Green Door is approached.
2. It doesn't recognize Heretic keys in player's inventory and keeps saying that key is required.

**Comment by Alando1-doom** [comment]
Way ahead of you. I will be implementing something that will replace/override the Red Key Checker. I will clone the Red Key Checker and renamed it to "Green Key Checker" and program it to look to see if the player has the Green Key in their inventory. The same can be done with both the Blue and Yellow Key Checkers. Fortunately, it's something easy to implement :)

**Comment by Alando1-doom** [comment]
I've just completed the new voiceovers and programmed the new key checkers. I've implemented a replacement system where the heretic key checkers will override the defaults.

**Comment by proydoha** [comment]
When you'll create pull request with new key checkers you can add `Closes #77` in PR description and this issue will be closed automatically when that PR will get merged
