### ISSUE TITLE
[Bug] Heretic multiplayer on TobyHereticMain.wad throws an error from Toby_QuickTurnHandler

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#81]
Version:
GZDoom 4.11.3

Load order:
- HERETIC.wad
- Toby-Accessibility-Mod-for-Doom
- TobyHereticMain.wad

Steps to reproduce:
1. Launch game with `-host 2` parameter
2. Launch game with `-join localhost` parameter

Expected result:
Multiplayer launched as usual in two GZDoom windows

Actual result:
Following error in both windows
```
E1M1 - The Docks

VM execution aborted: tried to read from address zero. In function parameter "self"
Called from Toby_QuickTurnHandler.PlayerEntered at zscript/quickturn.zs, line 6
Called from Actor.FindInventory [Native]
```

Notes:
Regular Doom multiplayer works just fine
Regular Heretic multiplayer works just fine

The issue seems to be in map but preventing the error would be preferable

**Comment by Alando1-doom** [comment]
I could look into it. All the maps (with the exception of the Demo map) are all GZDoom: Heretic in Doom format. Nothing is UDMF. It is a bit of a weird glitch but I'm sure there's a silly reason it happened.

**Comment by proydoha** [comment]
I think this was fixed. I'm not crashing anymore.
