### ISSUE TITLE
[Compatibility] Move some menu definitions to separate addon

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#86]
Will it be okay to move 

`LISTMENU "MainMenu"`

And

`OptionMenu "SimpleOptionsMenu"`

to separate addon?

The reason for this is that Toby Accessibility Mod overrides intended menus when loaded on top of the iwad / ipk3
This should improve compatibility with total conversions and commercial games.

**Comment by Alando1-doom** [comment]
We could put it in a separate add-on file. So far, this seems to be a safer way to do things. I've just separated the Key Checker Beacons from the core mod and made a separate add-on repository for it. I've done the same thing with the Heretic Key Checker Beacons, too, and it works very well. If you'd like to work on this separate menu piece, by all means feel free to do so :)
