### ISSUE TITLE
[Bug] Separation of the doors issue

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#92]
When doors were separated into their own addon core addon lost an ability to be loaded independently.

We're getting an error from linespawner.zs because it tries to spawn actors that are no longer there.

**Comment by Alando1-doom** [comment]
Everything loaded successfully on my end. This is what I have in the Doom batch files:
gzdoom.exe -config TobyConfig.ini -file TobyAccMod_V7-5.pk3 "./Addons/DOOM/TobyV7_Guns.pk3" "./Addons/DOOM/TobyV7_Monsters.pk3" "./Addons/DOOM/TobyV7_Pickups.pk3" "./Addons/DOOM/TobyV7_Decorations.pk3" "./Addons/DOOM/TobyV7_Beacons.pk3"

And this is what I have for the Heretic batch files:

gzdoom.exe -config TobyConfig.ini -file TobyAccMod_V7-5.pk3 "./Addons/HERETIC/TobyHereticWeapons.pk3" "./Addons/HERETIC/TobyHereticMonsters.pk3" "./Addons/HERETIC/TobyHereticItems.pk3" "./Addons/HERETIC/TobyHereticDecorations.pk3" "./Addons/HERETIC/TobyHereticBeacons.pk3"

The Beacon add-ons have the Key Door Checker Beacons. The Core mod is able to read the scripts in the Beacon add-on files and the linespawner.zs will be able to spawn the designated Key Checker Beacons.

**Comment by proydoha** [comment]
Try to load only TobyAccMod_V7-5 with no addons

**Comment by Alando1-doom** [comment]
Even though the Core mod will have an issue without the Beacon add-ons, this was the only way I could get the Heretic beacons to work properly. I could investigate other options but, as it stands, allowing the respected Beacon add-ons to be interchangeable seems to be the best way for the system to work. I might look into the DECORATE function where you can specify what game the actor is allowed to appear in. This could be an acceptable alternative. I will have to run some tests to see if it is possible. If this works, I can reincorporate the beacons into the Core mod.

**Comment by proydoha** [comment]
If this doesn't work I'll think about something else but I don't have capacity for it right now.

**Comment by proydoha** [comment]
I think this issue was fixed, I'm closing it.
